import React, { createContext, useContext, useState, useEffect } from 'react';
import i18n from '../i18n';

type Language = {
  code: string;
  name: string;
  flag: string;
  region: string;
};

type LanguageContextType = {
  currentLanguage: Language;
  setLanguage: (language: Language) => void;
  languages: Language[];
  t: (key: string) => string;
};

const languages: Language[] = [
  { code: 'en', name: 'English', flag: '🇬🇧', region: 'International' },
  { code: 'hi', name: 'हिंदी', flag: '🇮🇳', region: 'National' },
  { code: 'as', name: 'অসমীয়া', flag: '🇮🇳', region: 'Assam' },
  { code: 'bodo', name: 'बड़ो', flag: '🇮🇳', region: 'Assam' },
  { code: 'karbi', name: 'কার্বি', flag: '🇮🇳', region: 'Assam' },
  { code: 'mishing', name: 'মিচিং', flag: '🇮🇳', region: 'Assam' },
  { code: 'mni', name: 'মৈতৈলোন্', flag: '🇮🇳', region: 'Manipur' },
  { code: 'khasi', name: 'খাসি', flag: '🇮🇳', region: 'Meghalaya' },
  { code: 'garo', name: 'গারো', flag: '🇮🇳', region: 'Meghalaya' },
  { code: 'jaintia', name: 'জয়ন্তীয়া', flag: '🇮🇳', region: 'Meghalaya' },
  { code: 'mizo', name: 'মিজো', flag: '🇮🇳', region: 'Mizoram' },
  { code: 'nagamese', name: 'নাগামিজ', flag: '🇮🇳', region: 'Nagaland' },
  { code: 'ao', name: 'আও', flag: '🇮🇳', region: 'Nagaland' },
  { code: 'angami', name: 'আঙামি', flag: '🇮🇳', region: 'Nagaland' },
  { code: 'sema', name: 'সেমা', flag: '🇮🇳', region: 'Nagaland' },
  { code: 'lotha', name: 'লোথা', flag: '🇮🇳', region: 'Nagaland' },
  { code: 'nyishi', name: 'নিশি', flag: '🇮🇳', region: 'Arunachal Pradesh' },
  { code: 'apatani', name: 'আপাতানি', flag: '🇮🇳', region: 'Arunachal Pradesh' },
  { code: 'adi', name: 'আদি', flag: '🇮🇳', region: 'Arunachal Pradesh' },
  { code: 'mishmi', name: 'মিশমি', flag: '🇮🇳', region: 'Arunachal Pradesh' },
  { code: 'monpa', name: 'মনপা', flag: '🇮🇳', region: 'Arunachal Pradesh' },
  { code: 'tripuri', name: 'ত্রিপুরি', flag: '🇮🇳', region: 'Tripura' },
  { code: 'kokborok', name: 'ককবরক', flag: '🇮🇳', region: 'Tripura' },
  { code: 'bn', name: 'বাংলা', flag: '🇮🇳', region: 'Tripura' },
  { code: 'ne', name: 'नेपाली', flag: '🇮🇳', region: 'Sikkim' },
];

const translations: Record<string, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.report': 'Report Issue',
    'nav.alerts': 'Check Alerts',
    'nav.awareness': 'Awareness',
    'nav.login': 'Login',
    'hero.title': 'Smart Community Health Monitoring System',
    'hero.subtitle': 'Report, Monitor & Prevent Water-borne Diseases in Your Community',
    'hero.report_btn': 'Report Health Issue',
    'hero.check_btn': 'Check Water Quality',
    'stats.active_alerts': 'Active Alerts',
    'stats.reports_today': 'Reports Today',
    'stats.water_status': 'Water Quality Status',
    'awareness.title': 'Health Awareness',
    'login.title': 'Login to Your Account',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.submit': 'Sign In',
    'login.forgot': 'Forgot Password?',
    'login.no_account': "Don't have an account?",
    'login.signup': 'Sign Up',
    'report.title': 'Report Health Issue',
    'report.description': 'Help your community by reporting health concerns',
    'report.name': 'Full Name',
    'report.email': 'Email Address',
    'report.phone': 'Phone Number',
    'report.location': 'Location/Address',
    'report.issue_type': 'Issue Type',
    'report.symptoms': 'Symptoms Description',
    'report.severity': 'Severity Level',
    'report.submit': 'Submit Report',
    'alerts.title': 'Health Alerts',
    'alerts.description': 'Stay informed about health issues in your area',
    'alerts.no_alerts': 'No active alerts',
    'awareness.description': 'Learn about water-borne diseases and prevention',
    'dashboard.welcome': 'Welcome to Dashboard',
    'dashboard.overview': 'Overview',
    'dashboard.reports': 'Reports',
    'dashboard.alerts': 'Alerts',
    'dashboard.users': 'Users',
    'nav.water_quality': 'Water Quality',
    'water_quality.title': 'Water Quality Testing',
    'water_quality.subtitle': 'Submit comprehensive water quality data to help monitor and improve water safety in your community',
    'water_quality.basic_info': 'Basic Information',
    'water_quality.source_info': 'Water Source Information',
    'water_quality.physical_params': 'Physical Parameters',
    'water_quality.chemical_params': 'Chemical Parameters',
    'water_quality.biological_params': 'Biological Parameters',
    'water_quality.images': 'Water Sample Images',
    'water_quality.notes': 'Additional Notes',
    'water_quality.submit': 'Submit Water Quality Report',
    'water_quality.success': 'Submission Successful!',
    'water_quality.success_msg': 'Your water quality report has been submitted successfully.',
    'water_quality.success_sub': 'Our team will analyze the data and get back to you soon.',
  },
  hi: {
    'nav.home': 'होम',
    'nav.report': 'समस्या रिपोर्ट करें',
    'nav.alerts': 'अलर्ट जांचें',
    'nav.awareness': 'जागरूकता',
    'nav.login': 'लॉगिन',
    'hero.title': 'स्मार्ट सामुदायिक स्वास्थ्य निगरानी प्रणाली',
    'hero.subtitle': 'अपने समुदाय में जल जनित रोगों की रिपोर्ट, निगरानी और रोकथाम करें',
    'hero.report_btn': 'स्वास्थ्य समस्या रिपोर्ट करें',
    'hero.check_btn': 'पानी की गुणवत्ता जांचें',
    'stats.active_alerts': 'सक्रिय अलर्ट',
    'stats.reports_today': 'आज की रिपोर्ट',
    'stats.water_status': 'पानी की गुणवत्ता की स्थिति',
    'awareness.title': 'स्वास्थ्य जागरूकता',
    'login.title': 'अपने खाते में लॉगिन करें',
    'login.email': 'ईमेल पता',
    'login.password': 'पासवर्ड',
    'login.submit': 'साइन इन करें',
    'login.forgot': 'पासवर्ड भूल गए?',
    'login.no_account': 'खाता नहीं है?',
    'login.signup': 'साइन अप करें',
    'report.title': 'स्वास्थ्य समस्या रिपोर्ट करें',
    'report.description': 'स्वास्थ्य संबंधी चिंताओं की रिपोर्ट करके अपने समुदाय की मदद करें',
    'report.name': 'पूरा नाम',
    'report.email': 'ईमेल पता',
    'report.phone': 'फोन नंबर',
    'report.location': 'स्थान/पता',
    'report.issue_type': 'समस्या का प्रकार',
    'report.symptoms': 'लक्षणों का विवरण',
    'report.severity': 'गंभीरता का स्तर',
    'report.submit': 'रिपोर्ट सबमिट करें',
    'alerts.title': 'स्वास्थ्य अलर्ट',
    'alerts.description': 'अपने क्षेत्र में स्वास्थ्य समस्याओं के बारे में जानकारी रखें',
    'alerts.no_alerts': 'कोई सक्रिय अलर्ट नहीं',
    'awareness.description': 'जल जनित रोगों और उनकी रोकथाम के बारे में जानें',
    'dashboard.welcome': 'डैशबोर्ड में आपका स्वागत है',
    'dashboard.overview': 'अवलोकन',
    'dashboard.reports': 'रिपोर्ट',
    'dashboard.alerts': 'अलर्ट',
    'dashboard.users': 'उपयोगकर्ता',
    'nav.water_quality': 'पानी की गुणवत्ता',
    'water_quality.title': 'पानी की गुणवत्ता परीक्षण',
    'water_quality.subtitle': 'अपने समुदाय में पानी की सुरक्षा की निगरानी और सुधार में मदद करने के लिए व्यापक पानी की गुणवत्ता डेटा सबमिट करें',
    'water_quality.basic_info': 'बुनियादी जानकारी',
    'water_quality.source_info': 'पानी के स्रोत की जानकारी',
    'water_quality.physical_params': 'भौतिक मापदंड',
    'water_quality.chemical_params': 'रासायनिक मापदंड',
    'water_quality.biological_params': 'जैविक मापदंड',
    'water_quality.images': 'पानी के नमूने की छवियां',
    'water_quality.notes': 'अतिरिक्त नोट्स',
    'water_quality.submit': 'पानी की गुणवत्ता रिपोर्ट सबमिट करें',
    'water_quality.success': 'सबमिशन सफल!',
    'water_quality.success_msg': 'आपकी पानी की गुणवत्ता रिपोर्ट सफलतापूर्वक सबमिट की गई है।',
    'water_quality.success_sub': 'हमारी टीम डेटा का विश्लेषण करेगी और जल्द ही आपसे संपर्क करेगी।',
  },
  as: {
    'nav.home': 'ঘৰ',
    'nav.report': 'সমস্যা ৰিপৰ্ট কৰক',
    'nav.alerts': 'সতৰ্কবাণী পৰীক্ষা কৰক',
    'nav.awareness': 'সজাগতা',
    'nav.login': 'লগইন',
    'hero.title': 'স্মাৰ্ট সম্প্ৰদায়িক স্বাস্থ্য নিৰীক্ষণ ব্যৱস্থা',
    'hero.subtitle': 'আপোনাৰ সম্প্ৰদায়ত পানীবাহিত ৰোগৰ ৰিপৰ্ট, নিৰীক্ষণ আৰু প্ৰতিৰোধ কৰক',
    'hero.report_btn': 'স্বাস্থ্য সমস্যা ৰিপৰ্ট কৰক',
    'hero.check_btn': 'পানীৰ গুণগত মান পৰীক্ষা কৰক',
    'stats.active_alerts': 'সক্ৰিয় সতৰ্কবাণী',
    'stats.reports_today': 'আজিৰ ৰিপৰ্ট',
    'stats.water_status': 'পানীৰ গুণগত মানৰ অৱস্থা',
    'awareness.title': 'স্বাস্থ্য সজাগতা',
    'login.title': 'আপোনাৰ একাউণ্টত লগইন কৰক',
    'login.email': 'ইমেইল ঠিকনা',
    'login.password': 'পাছৱৰ্ড',
    'login.submit': 'ছাইন ইন কৰক',
    'login.forgot': 'পাছৱৰ্ড পাহৰি গ\'ল?',
    'login.no_account': 'একাউণ্ট নাই?',
    'login.signup': 'ছাইন আপ কৰক',
    'report.title': 'স্বাস্থ্য সমস্যা ৰিপৰ্ট কৰক',
    'report.description': 'স্বাস্থ্য সম্পৰ্কীয় উদ্বেগ ৰিপৰ্ট কৰি আপোনাৰ সম্প্ৰদায়ক সহায় কৰক',
    'report.name': 'পূৰ্ণ নাম',
    'report.email': 'ইমেইল ঠিকনা',
    'report.phone': 'ফোন নম্বৰ',
    'report.location': 'স্থান/ঠিকনা',
    'report.issue_type': 'সমস্যাৰ প্ৰকাৰ',
    'report.symptoms': 'লক্ষণৰ বৰ্ণনা',
    'report.severity': 'গুৰুত্বৰ স্তৰ',
    'report.submit': 'ৰিপৰ্ট দাখিল কৰক',
    'alerts.title': 'স্বাস্থ্য সতৰ্কবাণী',
    'alerts.description': 'আপোনাৰ অঞ্চলত স্বাস্থ্য সমস্যাবোৰৰ বিষয়ে জানি থাকক',
    'alerts.no_alerts': 'কোনো সক্ৰিয় সতৰ্কবাণী নাই',
    'awareness.description': 'পানীবাহিত ৰোগ আৰু ইয়াৰ প্ৰতিৰোধৰ বিষয়ে জানক',
    'dashboard.welcome': 'ডেচবোৰ্ডলৈ স্বাগতম',
    'dashboard.overview': 'সামগ্ৰিক দৃষ্টিভংগী',
    'dashboard.reports': 'ৰিপৰ্টসমূহ',
    'dashboard.alerts': 'সতৰ্কবাণীসমূহ',
    'dashboard.users': 'ব্যৱহাৰকাৰীসকল',
  },
  bodo: {
    'nav.home': 'गिदिनाव',
    'nav.report': 'समस्या रिपोर्ट खालाम',
    'nav.alerts': 'जागोनखौ नाय',
    'nav.awareness': 'सचेतना',
    'nav.login': 'हाब',
    'hero.title': 'स्मार्ट समाजिक सांग्रां नायगिदिमगिरि बिथिं',
    'hero.subtitle': 'नोंथांनि समाजयो दै सिनाय जानाय बेरामखौ रिपोर्ट, नायगिदिम आरो हाब',
    'hero.report_btn': 'सुबुं बेरामखौ रिपोर्ट खालाम',
    'hero.check_btn': 'दैनि गुनखौ नाय',
    'stats.active_alerts': 'हाबग्रा जागोन',
    'stats.reports_today': 'बे मोनि रिपोर्ट',
    'stats.water_status': 'दैनि गुननि थावनि',
    'awareness.title': 'सुबुं सचेतना',
    'login.title': 'नोंथांनि अकाउंटआव हाब',
    'login.email': 'इमेल थुन्थि',
    'login.password': 'पासवर्ड',
    'login.submit': 'साइन इन खालाम',
    'login.forgot': 'पासवर्ड बोरिबो',
    'login.no_account': 'अकाउंट गैया?',
    'login.signup': 'साइन अप खालाम',
    'report.title': 'सुबुं बेरामखौ रिपोर्ट खालाम',
    'report.description': 'सुबुंनि चिन्ताखौ रिपोर्ट खालामनानै नोंथांनि समाजयो माबा',
    'report.name': 'बांद्राय मुं',
    'report.email': 'इमेल थुन्थि',
    'report.phone': 'फोन नम्बर',
    'report.location': 'थावनि/थुन्थि',
    'report.issue_type': 'समस्यानि रकम',
    'report.symptoms': 'बेरावनि बिबर',
    'report.severity': 'गिदिमनायनि थावनि',
    'report.submit': 'रिपोर्ट होब',
    'alerts.title': 'सुबुं जागोन',
    'alerts.description': 'नोंथांनि थाउनाव सुबुंनि बेरामफोरनि बारे जानो थाखो',
    'alerts.no_alerts': 'मोनि सक्रिय अलर्ट नांगो',
    'awareness.description': 'दै सिनाय जानाय बेराम आरो इनि हाबनि बारे जानो',
    'dashboard.welcome': 'डैशबोर्डआव खुलुमदों',
    'dashboard.overview': 'माबा नाय',
    'dashboard.reports': 'रिपोर्टफोर',
    'dashboard.alerts': 'जागोनफोर',
    'dashboard.users': 'बाहायगिरिफोर',
  },
  karbi: {
    'nav.home': 'আছি',
    'nav.report': 'আৰুং হিপোৰ্ট',
    'nav.alerts': 'চেক আৰুৎ‌',
    'nav.awareness': 'সজাগতা',
    'nav.login': 'লগইন',
    'hero.title': 'স্মার্ট কমিউনিটি স্বাস্থ্য নিৰীক্ষণ সিষ্টেম',
    'hero.subtitle': 'আছি কমিউনিটি আৱৰণ হিঁপিলে পানীৰ ৰোগৰ ৰিপোৰ্ট, নিৰীক্ষণ, আৰু প্ৰতিৰোধ',
    'hero.report_btn': 'স্বাস্থ্য আৰুৎ হিপোৰ্ট',
    'hero.check_btn': 'পানীৰ মান চেক',
    'stats.active_alerts': 'সক্ৰিয় আৰুৎ',
    'stats.reports_today': 'আজিৰ হিপোৰ্ট',
    'stats.water_status': 'পানীৰ মান অৱস্থা',
    'awareness.title': 'স্বাস্থ্য সজাগতা',
    'login.title': 'আছি একাউন্টত লগইন',
    'login.email': 'ইমেইল',
    'login.password': 'পাছৱৰ্ড',
    'login.submit': 'লগইন কৰক',
    'login.forgot': 'পাছৱৰ্ড পাহৰি গ’ল?',
    'login.no_account': 'একাউন্ট নাই?',
    'login.signup': 'সাইন আপ',
    'report.title': 'স্বাস্থ্য আৰুৎ হিপোৰ্ট',
    'report.description': 'আছি কমিউনিটিক স্বাস্থ্য বিষয়ত সহায় কৰক',
    'report.name': 'পূৰা নাম',
    'report.email': 'ইমেইল',
    'report.phone': 'ফোন নং',
    'report.location': 'স্থান/ঠিকনা',
    'report.issue_type': 'আৰুৎ ৰকম',
    'report.symptoms': 'লক্ষ্য হিপোৰ্ট',
    'report.severity': 'গুৰুত্ব লেভেল',
    'report.submit': 'হিপোৰ্ট জমা কৰক',
    'alerts.title': 'স্বাস্থ্য আৰুৎ',
    'alerts.description': 'আছি এৰিয়াত স্বাস্থ্য বিষয়ত সচেতন থাকক',
    'alerts.no_alerts': 'কোনো সক্ৰিয় আৰুৎ নাই',
    'awareness.description': 'পানীৰ ৰোগ আৰু ইয়াৰ প্ৰতিৰোধৰ বিষয়ে জানক',
    'dashboard.welcome': 'ডেশব’ৰ্ডলৈ স্বাগতম',
    'dashboard.overview': 'ওভাৰভিউ',
    'dashboard.reports': 'হিপোৰ্ট',
    'dashboard.alerts': 'আৰুৎ',
    'dashboard.users': 'ইউজাৰ',
  },
  mishing: {
    'nav.home': 'হোম',
    'nav.report': 'সমস্যা ৰিপোৰ্ট',
    'nav.alerts': 'আলাৰ্ট চেক',
    'nav.awareness': 'সজাগতা',
    'nav.login': 'লগইন',
    'hero.title': 'স্মার্ট কমিউনিটি স্বাস্থ্য পৰিচৰ্যা চিষ্টেম',
    'hero.subtitle': 'আপোনাৰ কমিউনিটিত পানীত সংক্ৰমিত ৰোগবোৰ ৰিপোৰ্ট, নিৰীক্ষণ আৰু প্ৰতিৰোধ কৰক',
    'hero.report_btn': 'স্বাস্থ্য সমস্যা ৰিপোৰ্ট',
    'hero.check_btn': 'পানীৰ মানদণ্ড চেক',
    'stats.active_alerts': 'সক্ৰিয় আলাৰ্ট',
    'stats.reports_today': 'আজিৰ ৰিপোৰ্ট',
    'stats.water_status': 'পানীৰ মানদণ্ড স্থিতি',
    'awareness.title': 'স্বাস্থ্য সজাগতা',
    'login.title': 'আপোনাৰ একাউণ্টত লগইন',
    'login.email': 'ইমেইল',
    'login.password': 'পাছৱৰ্ড',
    'login.submit': 'লগইন কৰক',
    'login.forgot': 'পাছৱৰ্ড পাহৰি গ’ল?',
    'login.no_account': 'একাউণ্ট নাই?',
    'login.signup': 'সাইন আপ',
    'report.title': 'স্বাস্থ্য সমস্যা ৰিপোৰ্ট',
    'report.description': 'স্বাস্থ্য সমস্যা ৰিপোৰ্ট কৰি আপোনাৰ কমিউনিটিক সহায় কৰক',
    'report.name': 'পূৰা নাম',
    'report.email': 'ইমেইল',
    'report.phone': 'ফোন নং',
    'report.location': 'স্থান/ঠিকনা',
    'report.issue_type': 'সমস্যাৰ প্ৰকাৰ',
    'report.symptoms': 'লক্ষ্য বিৱৰণ',
    'report.severity': 'গুৰুত্বৰ স্তৰ',
    'report.submit': 'ৰিপোৰ্ট জমা কৰক',
    'alerts.title': 'স্বাস্থ্য আলাৰ্ট',
    'alerts.description': 'আপোনাৰ এলেকাত স্বাস্থ্য সমস্যাবোৰৰ বিষয়ে জানি থাকক',
    'alerts.no_alerts': 'কোনো সক্ৰিয় আলাৰ্ট নাই',
    'awareness.description': 'পানী সংক্ৰমিত ৰোগ আৰু ইয়াৰ প্ৰতিৰোধৰ বিষয়ে শিকক',
    'dashboard.welcome': 'ডেশ্ববোর্ডলৈ স্বাগতম',
    'dashboard.overview': 'ওভাৰভিউ',
    'dashboard.reports': 'ৰিপোৰ্ট',
    'dashboard.alerts': 'আলাৰ্ট',
    'dashboard.users': 'ইউজাৰ',
  },
  mni: {
    'nav.home': 'য়ুম',
    'nav.report': 'অসুবিধা রিপোর্ত তৌবা',
    'nav.alerts': 'চেক্তুনা য়েংবা',
    'nav.awareness': 'লৌশিংবা',
    'nav.login': 'চংশিনবা',
    'hero.title': 'স্মার্ত কম্যুনিতি স্বাস্থ্য য়েংবগী সিস্তেম',
    'hero.subtitle': 'নহাক্কী কম্যুনিতিদা ইশিংগী লাইবক অসোয়বা রিপোর্ত, য়েংবা অমসুং থিংবা',
    'hero.report_btn': 'স্বাস্থ্য অসোয়বা রিপোর্ত তৌবা',
    'hero.check_btn': 'ইশিংগী মশক য়েংবা',
    'stats.active_alerts': 'শীজিন্নবা চেক্তুনা',
    'stats.reports_today': 'ইংঙেই রিপোর্তশিং',
    'stats.water_status': 'ইশিংগী মশকগী অবা',
    'awareness.title': 'স্বাস্থ্য লৌশিংবা',
    'login.title': 'নহাক্কী একাউন্টদা চংশিনবা',
    'login.email': 'ইমেইল থিকনা',
    'login.password': 'পাসৱর্ড',
    'login.submit': 'সাইন ইন তৌবা',
    'login.forgot': 'পাসৱর্ড লৌরম্বা?',
    'login.no_account': 'একাউন্ট নাই?',
    'login.signup': 'সাইন আপ তৌবা',
    'report.title': 'স্বাস্থ্য অসোয়বা রিপোর্ত তৌবা',
    'report.description': 'স্বাস্থ্য সম্পরকীয় উদ্বেগ রিপোর্ত তৌবা অমসুং নহাক্কী কম্যুনিতিক সাহায়্য তৌবা',
    'report.name': 'পূর্ন নাম',
    'report.email': 'ইমেইল থিকনা',
    'report.phone': 'ফোন নম্বর',
    'report.location': 'থান/থিকনা',
    'report.issue_type': 'অসোয়বগী প্রকার',
    'report.symptoms': 'লক্ষণগী বর্ণনা',
    'report.severity': 'গম্ভীরতাগী স্তর',
    'report.submit': 'রিপোর্ত দাখিল তৌবা',
    'alerts.title': 'স্বাস্থ্য চেক্তুনা',
    'alerts.description': 'নহাক্কী থানদা স্বাস্থ্য অসোয়বগী বারে চান্না থৌ',
    'alerts.no_alerts': 'মরাংবা শীজিন্নবা চেক্তুনা নাই',
    'awareness.description': 'ইশিংগী লাইবক অসোয়বা অমসুং ইগী থিংবগী বারে চান্না',
    'dashboard.welcome': 'ডাশবর্ডদা স্বাগতম',
    'dashboard.overview': 'সামগ্রিক দৃষ্টিভংগী',
    'dashboard.reports': 'রিপোর্তশিং',
    'dashboard.alerts': 'চেক্তুনাশিং',
    'dashboard.users': 'বাহায়গিরিশিং',
  },
  khasi: {
    'nav.home': 'Iing',
    'nav.report': 'Pynmih jingeh',
    'nav.alerts': 'Peit ki Alert',
    'nav.awareness': 'Jingsngewthuh',
    'nav.login': 'Shon',
    'hero.title': 'Ka Smart Community Health Monitoring System',
    'hero.subtitle': 'Pynmih, peit, bad iada na ki jingpang ba wan na ka um ha ka community jong phi',
    'hero.report_btn': 'Pynmih Jingeh ha ka Koit ka Khiah',
    'hero.check_btn': 'Peit ia ka jinglong ka um',
    'stats.active_alerts': 'Ki Active Alerts',
    'stats.reports_today': 'Ki Reports mynta ka sngi',
    'stats.water_status': 'Jinglong ka um',
    'awareness.title': 'Jingsngewthuh ha ka Koit ka Khiah',
    'login.title': 'Shon sha ka Account jong phi',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.submit': 'Shon ha ka Shon-in',
    'login.forgot': 'Klet Password?',
    'login.no_account': 'Ym don Account?',
    'login.signup': 'Shon ha ka Sign-up',
    'report.title': 'Pynmih Jingeh ha ka Koit ka Khiah',
    'report.description': 'Iarap ia ka community jong phi da kaba pynmih ki jingeh ha ka koit ka khiah',
    'report.name': 'Ka kyrteng kaba pura',
    'report.email': 'Email Address',
    'report.phone': 'Ka Mobile No',
    'report.location': 'Ka jaka/Ka Address',
    'report.issue_type': 'Ka jingeh',
    'report.symptoms': 'Ka jingbatai ia ki sympton',
    'report.severity': 'Ka jingeh',
    'report.submit': 'Pynmih ia ka Report',
    'alerts.title': 'Ki Health Alerts',
    'alerts.description': 'Pynmih ia ki jingpynbna ha ka jaka jong phi',
    'alerts.no_alerts': 'Ym don ki active alerts',
    'awareness.description': 'Pule shaphang ki jingpang ba wan na ka um bad ka jingiada',
    'dashboard.welcome': 'Sngewbha sha ka Dashboard',
    'dashboard.overview': 'Ka jingbatai',
    'dashboard.reports': 'Ki Reports',
    'dashboard.alerts': 'Ki Alerts',
    'dashboard.users': 'Ki Nongtrei',
  },
  garo: {
    'nav.home': 'Nok',
    'nav.report': 'Neng∙nikaniko Ong∙atbo',
    'nav.alerts': 'Alert-rangko Niboe',
    'nav.awareness': 'Ma∙sisianiko Gualbo',
    'nav.login': 'Napbo',
    'hero.title': 'Smart Community Health Monitoring System',
    'hero.subtitle': 'Neng∙nikaniko Ong∙atna, Simzakina Aro An∙sengtina Gualaniko Gualbo',
    'hero.report_btn': 'Neng∙nikaniko Ong∙atna',
    'hero.check_btn': 'Chiningko Gualbo',
    'stats.active_alerts': 'Ong∙gipa Alert',
    'stats.reports_today': 'Dingo Ong∙gipa Report',
    'stats.water_status': 'Chiningko Ong∙gipa Obostarangko Gualbo',
    'awareness.title': 'Ma∙sisianiko Gualbo',
    'login.title': 'Napbo',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.submit': 'Napbo',
    'login.forgot': 'Password-ko Gualbo?',
    'login.no_account': 'Account-ko Ong∙atbo',
    'login.signup': 'Sign Up',
    'report.title': 'Neng∙nikaniko Ong∙atna',
    'report.description': 'Neng∙nikaniko Ong∙atna aro An∙sengtina Gualaniko Gualbo',
    'report.name': 'Mingni',
    'report.email': 'Email Address',
    'report.phone': 'Mobile Number',
    'report.location': 'Jagamiko/Address',
    'report.issue_type': 'Neng∙nikaniko Ong∙atna',
    'report.symptoms': 'Neng∙nikaniko Ong∙atna',
    'report.severity': 'Neng∙nikaniko Ong∙atna',
    'report.submit': 'Ong∙atbo',
    'alerts.title': 'Alert-rangko Niboe',
    'alerts.description': 'Alert-rangko Niboe',
    'alerts.no_alerts': 'Alert-rangko Niboe',
    'awareness.description': 'Alert-rangko Niboe',
    'dashboard.welcome': 'Dashboard-ko Niboe',
    'dashboard.overview': 'Dashboard-ko Niboe',
    'dashboard.reports': 'Dashboard-ko Niboe',
    'dashboard.alerts': 'Dashboard-ko Niboe',
    'dashboard.users': 'Dashboard-ko Niboe',
  },
  jaintia: {
    'nav.home': 'Ing',
    'nav.report': 'Pynmih jingeh',
    'nav.alerts': 'Peit ki Alert',
    'nav.awareness': 'Jingsngewthuh',
    'nav.login': 'Shon',
    'hero.title': 'Ka Smart Community Health Monitoring System',
    'hero.subtitle': 'Pynmih, peit, bad iada na ki jingpang ba wan na ka um ha ka community jong phi',
    'hero.report_btn': 'Pynmih Jingeh ha ka Koit ka Khiah',
    'hero.check_btn': 'Peit ia ka jinglong ka um',
    'stats.active_alerts': 'Ki Active Alerts',
    'stats.reports_today': 'Ki Reports mynta ka sngi',
    'stats.water_status': 'Jinglong ka um',
    'awareness.title': 'Jingsngewthuh ha ka Koit ka Khiah',
    'login.title': 'Shon sha ka Account jong phi',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.submit': 'Shon ha ka Shon-in',
    'login.forgot': 'Klet Password?',
    'login.no_account': 'Ym don Account?',
    'login.signup': 'Shon ha ka Sign-up',
    'report.title': 'Pynmih Jingeh ha ka Koit ka Khiah',
    'report.description': 'Iarap ia ka community jong phi da kaba pynmih ki jingeh ha ka koit ka khiah',
    'report.name': 'Ka kyrteng kaba pura',
    'report.email': 'Email Address',
    'report.phone': 'Ka Mobile No',
    'report.location': 'Ka jaka/Ka Address',
    'report.issue_type': 'Ka jingeh',
    'report.symptoms': 'Ka jingbatai ia ki sympton',
    'report.severity': 'Ka jingeh',
    'report.submit': 'Pynmih ia ka Report',
    'alerts.title': 'Ki Health Alerts',
    'alerts.description': 'Pynmih ia ki jingpynbna ha ka jaka jong phi',
    'alerts.no_alerts': 'Ym don ki active alerts',
    'awareness.description': 'Pule shaphang ki jingpang ba wan na ka um bad ka jingiada',
    'dashboard.welcome': 'Sngewbha sha ka Dashboard',
    'dashboard.overview': 'Ka jingbatai',
    'dashboard.reports': 'Ki Reports',
    'dashboard.alerts': 'Ki Alerts',
    'dashboard.users': 'Ki Nongtrei',
  },
  mizo: {
    'nav.home': 'In',
    'nav.report': 'Hriat tirh',
    'nav.alerts': 'Hriatna hrilh',
    'nav.awareness': 'Hriatna hrilh',
    'nav.login': 'Login',
    'hero.title': 'Hriatna hrilh',
    'hero.subtitle': 'Hriatna hrilh',
    'hero.report_btn': 'Hriatna hrilh',
    'hero.check_btn': 'Hriatna hrilh',
    'stats.active_alerts': 'Hriatna hrilh',
    'stats.reports_today': 'Hriatna hrilh',
    'stats.water_status': 'Hriatna hrilh',
    'awareness.title': 'Hriatna hrilh',
    'login.title': 'Hriatna hrilh',
    'login.email': 'Hriatna hrilh',
    'login.password': 'Hriatna hrilh',
    'login.submit': 'Hriatna hrilh',
    'login.forgot': 'Hriatna hrilh',
    'login.no_account': 'Hriatna hrilh',
    'login.signup': 'Hriatna hrilh',
    'report.title': 'Hriatna hrilh',
    'report.description': 'Hriatna hrilh',
    'report.name': 'Hriatna hrilh',
    'report.email': 'Hriatna hrilh',
    'report.phone': 'Hriatna hrilh',
    'report.location': 'Hriatna hrilh',
    'report.issue_type': 'Hriatna hrilh',
    'report.symptoms': 'Hriatna hrilh',
    'report.severity': 'Hriatna hrilh',
    'report.submit': 'Hriatna hrilh',
    'alerts.title': 'Hriatna hrilh',
    'alerts.description': 'Hriatna hrilh',
    'alerts.no_alerts': 'Hriatna hrilh',
    'awareness.description': 'Hriatna hrilh',
    'dashboard.welcome': 'Hriatna hrilh',
    'dashboard.overview': 'Hriatna hrilh',
    'dashboard.reports': 'Hriatna hrilh',
    'dashboard.alerts': 'Hriatna hrilh',
    'dashboard.users': 'Hriatna hrilh',
  },
  nagamese: {
    'nav.home': 'Ghor',
    'nav.report': 'Issue Report Koro',
    'nav.alerts': 'Alerts Check Koro',
    'nav.awareness': 'Awareness',
    'nav.login': 'Login',
    'hero.title': 'Smart Community Health Monitoring System',
    'hero.subtitle': 'Etia Pani-diseases Report, Monitor & Prevention',
    'hero.report_btn': 'Health Issue Report Koro',
    'hero.check_btn': 'Pani Quality Check Koro',
    'stats.active_alerts': 'Active Alerts',
    'stats.reports_today': 'Ajiya Report',
    'stats.water_status': 'Pani Quality Status',
    'awareness.title': 'Health Awareness',
    'login.title': 'Tumor Account Login Koro',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.submit': 'Sign In Koro',
    'login.forgot': 'Password Bhuli Gol?',
    'login.no_account': 'Account Nai?',
    'login.signup': 'Sign Up Koro',
    'report.title': 'Health Issue Report Koro',
    'report.description': 'Community ke health chinta report kori ke help koro',
    'report.name': 'Pura Naam',
    'report.email': 'Email Address',
    'report.phone': 'Phone Number',
    'report.location': 'Jaga/Address',
    'report.issue_type': 'Issue Type',
    'report.symptoms': 'Symptom Description',
    'report.severity': 'Severity Level',
    'report.submit': 'Report Submit Koro',
    'alerts.title': 'Health Alerts',
    'alerts.description': 'Tumor area te health issue khan jani rakho',
    'alerts.no_alerts': 'Kono active alert nai',
    'awareness.description': 'Pani-diseases aru rokhi rakha ke jani rakho',
    'dashboard.welcome': 'Dashboard te welcome koro',
    'dashboard.overview': 'Overview',
    'dashboard.reports': 'Reports',
    'dashboard.alerts': 'Alerts',
    'dashboard.users': 'Users',
  },
  ao: {
    'nav.home': 'Ochima',
    'nav.report': 'Problem Report',
    'nav.alerts': 'Alerts Check',
    'nav.awareness': 'Awareness',
    'nav.login': 'Login',
    'hero.title': 'Smart Community Health Monitoring System',
    'hero.subtitle': 'Pani-diseases Report, Monitor & Prevention',
    'hero.report_btn': 'Health Problem Report',
    'hero.check_btn': 'Water Quality Check',
    'stats.active_alerts': 'Active Alerts',
    'stats.reports_today': 'Today\'s Reports',
    'stats.water_status': 'Water Quality Status',
    'awareness.title': 'Health Awareness',
    'login.title': 'Login to Your Account',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.submit': 'Sign In',
    'login.forgot': 'Forgot Password?',
    'login.no_account': 'Don\'t have an account?',
    'login.signup': 'Sign Up',
    'report.title': 'Health Problem Report',
    'report.description': 'Help your community by reporting health concerns',
    'report.name': 'Full Name',
    'report.email': 'Email Address',
    'report.phone': 'Phone Number',
    'report.location': 'Location/Address',
    'report.issue_type': 'Problem Type',
    'report.symptoms': 'Symptoms Description',
    'report.severity': 'Severity Level',
    'report.submit': 'Submit Report',
    'alerts.title': 'Health Alerts',
    'alerts.description': 'Stay informed about health issues in your area',
    'alerts.no_alerts': 'No active alerts',
    'awareness.description': 'Learn about water-borne diseases and prevention',
    'dashboard.welcome': 'Welcome to Dashboard',
    'dashboard.overview': 'Overview',
    'dashboard.reports': 'Reports',
    'dashboard.alerts': 'Alerts',
    'dashboard.users': 'Users',
  },
  angami: {
    'nav.home': 'Nuo',
    'nav.report': 'Nuo',
    'nav.alerts': 'Nuo',
    'nav.awareness': 'Nuo',
    'nav.login': 'Nuo',
    'hero.title': 'Nuo',
    'hero.subtitle': 'Nuo',
    'hero.report_btn': 'Nuo',
    'hero.check_btn': 'Nuo',
    'stats.active_alerts': 'Nuo',
    'stats.reports_today': 'Nuo',
    'stats.water_status': 'Nuo',
    'awareness.title': 'Nuo',
    'login.title': 'Nuo',
    'login.email': 'Nuo',
    'login.password': 'Nuo',
    'login.submit': 'Nuo',
    'login.forgot': 'Nuo',
    'login.no_account': 'Nuo',
    'login.signup': 'Nuo',
    'report.title': 'Nuo',
    'report.description': 'Nuo',
    'report.name': 'Nuo',
    'report.email': 'Nuo',
    'report.phone': 'Nuo',
    'report.location': 'Nuo',
    'report.issue_type': 'Nuo',
    'report.symptoms': 'Nuo',
    'report.severity': 'Nuo',
    'report.submit': 'Nuo',
    'alerts.title': 'Nuo',
    'alerts.description': 'Nuo',
    'alerts.no_alerts': 'Nuo',
    'awareness.description': 'Nuo',
    'dashboard.welcome': 'Nuo',
    'dashboard.overview': 'Nuo',
    'dashboard.reports': 'Nuo',
    'dashboard.alerts': 'Nuo',
    'dashboard.users': 'Nuo',
  },
  sema: {
    'nav.home': 'Kuh',
    'nav.report': 'Kuh',
    'nav.alerts': 'Kuh',
    'nav.awareness': 'Kuh',
    'nav.login': 'Kuh',
    'hero.title': 'Kuh',
    'hero.subtitle': 'Kuh',
    'hero.report_btn': 'Kuh',
    'hero.check_btn': 'Kuh',
    'stats.active_alerts': 'Kuh',
    'stats.reports_today': 'Kuh',
    'stats.water_status': 'Kuh',
    'awareness.title': 'Kuh',
    'login.title': 'Kuh',
    'login.email': 'Kuh',
    'login.password': 'Kuh',
    'login.submit': 'Kuh',
    'login.forgot': 'Kuh',
    'login.no_account': 'Kuh',
    'login.signup': 'Kuh',
    'report.title': 'Kuh',
    'report.description': 'Kuh',
    'report.name': 'Kuh',
    'report.email': 'Kuh',
    'report.phone': 'Kuh',
    'report.location': 'Kuh',
    'report.issue_type': 'Kuh',
    'report.symptoms': 'Kuh',
    'report.severity': 'Kuh',
    'report.submit': 'Kuh',
    'alerts.title': 'Kuh',
    'alerts.description': 'Kuh',
    'alerts.no_alerts': 'Kuh',
    'awareness.description': 'Kuh',
    'dashboard.welcome': 'Kuh',
    'dashboard.overview': 'Kuh',
    'dashboard.reports': 'Kuh',
    'dashboard.alerts': 'Kuh',
    'dashboard.users': 'Kuh',
  },
  lotha: {
    'nav.home': 'Pung',
    'nav.report': 'Pung',
    'nav.alerts': 'Pung',
    'nav.awareness': 'Pung',
    'nav.login': 'Pung',
    'hero.title': 'Pung',
    'hero.subtitle': 'Pung',
    'hero.report_btn': 'Pung',
    'hero.check_btn': 'Pung',
    'stats.active_alerts': 'Pung',
    'stats.reports_today': 'Pung',
    'stats.water_status': 'Pung',
    'awareness.title': 'Pung',
    'login.title': 'Pung',
    'login.email': 'Pung',
    'login.password': 'Pung',
    'login.submit': 'Pung',
    'login.forgot': 'Pung',
    'login.no_account': 'Pung',
    'login.signup': 'Pung',
    'report.title': 'Pung',
    'report.description': 'Pung',
    'report.name': 'Pung',
    'report.email': 'Pung',
    'report.phone': 'Pung',
    'report.location': 'Pung',
    'report.issue_type': 'Pung',
    'report.symptoms': 'Pung',
    'report.severity': 'Pung',
    'report.submit': 'Pung',
    'alerts.title': 'Pung',
    'alerts.description': 'Pung',
    'alerts.no_alerts': 'Pung',
    'awareness.description': 'Pung',
    'dashboard.welcome': 'Pung',
    'dashboard.overview': 'Pung',
    'dashboard.reports': 'Pung',
    'dashboard.alerts': 'Pung',
    'dashboard.users': 'Pung',
  },
  nyishi: {
    'nav.home': 'Nii',
    'nav.report': 'Nii',
    'nav.alerts': 'Nii',
    'nav.awareness': 'Nii',
    'nav.login': 'Nii',
    'hero.title': 'Nii',
    'hero.subtitle': 'Nii',
    'hero.report_btn': 'Nii',
    'hero.check_btn': 'Nii',
    'stats.active_alerts': 'Nii',
    'stats.reports_today': 'Nii',
    'stats.water_status': 'Nii',
    'awareness.title': 'Nii',
    'login.title': 'Nii',
    'login.email': 'Nii',
    'login.password': 'Nii',
    'login.submit': 'Nii',
    'login.forgot': 'Nii',
    'login.no_account': 'Nii',
    'login.signup': 'Nii',
    'report.title': 'Nii',
    'report.description': 'Nii',
    'report.name': 'Nii',
    'report.email': 'Nii',
    'report.phone': 'Nii',
    'report.location': 'Nii',
    'report.issue_type': 'Nii',
    'report.symptoms': 'Nii',
    'report.severity': 'Nii',
    'report.submit': 'Nii',
    'alerts.title': 'Nii',
    'alerts.description': 'Nii',
    'alerts.no_alerts': 'Nii',
    'awareness.description': 'Nii',
    'dashboard.welcome': 'Nii',
    'dashboard.overview': 'Nii',
    'dashboard.reports': 'Nii',
    'dashboard.alerts': 'Nii',
    'dashboard.users': 'Nii',
  },
  apatani: {
    'nav.home': 'Dii',
    'nav.report': 'Dii',
    'nav.alerts': 'Dii',
    'nav.awareness': 'Dii',
    'nav.login': 'Dii',
    'hero.title': 'Dii',
    'hero.subtitle': 'Dii',
    'hero.report_btn': 'Dii',
    'hero.check_btn': 'Dii',
    'stats.active_alerts': 'Dii',
    'stats.reports_today': 'Dii',
    'stats.water_status': 'Dii',
    'awareness.title': 'Dii',
    'login.title': 'Dii',
    'login.email': 'Dii',
    'login.password': 'Dii',
    'login.submit': 'Dii',
    'login.forgot': 'Dii',
    'login.no_account': 'Dii',
    'login.signup': 'Dii',
    'report.title': 'Dii',
    'report.description': 'Dii',
    'report.name': 'Dii',
    'report.email': 'Dii',
    'report.phone': 'Dii',
    'report.location': 'Dii',
    'report.issue_type': 'Dii',
    'report.symptoms': 'Dii',
    'report.severity': 'Dii',
    'report.submit': 'Dii',
    'alerts.title': 'Dii',
    'alerts.description': 'Dii',
    'alerts.no_alerts': 'Dii',
    'awareness.description': 'Dii',
    'dashboard.welcome': 'Dii',
    'dashboard.overview': 'Dii',
    'dashboard.reports': 'Dii',
    'dashboard.alerts': 'Dii',
    'dashboard.users': 'Dii',
  },
  adi: {
    'nav.home': 'Rii',
    'nav.report': 'Rii',
    'nav.alerts': 'Rii',
    'nav.awareness': 'Rii',
    'nav.login': 'Rii',
    'hero.title': 'Rii',
    'hero.subtitle': 'Rii',
    'hero.report_btn': 'Rii',
    'hero.check_btn': 'Rii',
    'stats.active_alerts': 'Rii',
    'stats.reports_today': 'Rii',
    'stats.water_status': 'Rii',
    'awareness.title': 'Rii',
    'login.title': 'Rii',
    'login.email': 'Rii',
    'login.password': 'Rii',
    'login.submit': 'Rii',
    'login.forgot': 'Rii',
    'login.no_account': 'Rii',
    'login.signup': 'Rii',
    'report.title': 'Rii',
    'report.description': 'Rii',
    'report.name': 'Rii',
    'report.email': 'Rii',
    'report.phone': 'Rii',
    'report.location': 'Rii',
    'report.issue_type': 'Rii',
    'report.symptoms': 'Rii',
    'report.severity': 'Rii',
    'report.submit': 'Rii',
    'alerts.title': 'Rii',
    'alerts.description': 'Rii',
    'alerts.no_alerts': 'Rii',
    'awareness.description': 'Rii',
    'dashboard.welcome': 'Rii',
    'dashboard.overview': 'Rii',
    'dashboard.reports': 'Rii',
    'dashboard.alerts': 'Rii',
    'dashboard.users': 'Rii',
  },
  mishmi: {
    'nav.home': 'Bii',
    'nav.report': 'Bii',
    'nav.alerts': 'Bii',
    'nav.awareness': 'Bii',
    'nav.login': 'Bii',
    'hero.title': 'Bii',
    'hero.subtitle': 'Bii',
    'hero.report_btn': 'Bii',
    'hero.check_btn': 'Bii',
    'stats.active_alerts': 'Bii',
    'stats.reports_today': 'Bii',
    'stats.water_status': 'Bii',
    'awareness.title': 'Bii',
    'login.title': 'Bii',
    'login.email': 'Bii',
    'login.password': 'Bii',
    'login.submit': 'Bii',
    'login.forgot': 'Bii',
    'login.no_account': 'Bii',
    'login.signup': 'Bii',
    'report.title': 'Bii',
    'report.description': 'Bii',
    'report.name': 'Bii',
    'report.email': 'Bii',
    'report.phone': 'Bii',
    'report.location': 'Bii',
    'report.issue_type': 'Bii',
    'report.symptoms': 'Bii',
    'report.severity': 'Bii',
    'report.submit': 'Bii',
    'alerts.title': 'Bii',
    'alerts.description': 'Bii',
    'alerts.no_alerts': 'Bii',
    'awareness.description': 'Bii',
    'dashboard.welcome': 'Bii',
    'dashboard.overview': 'Bii',
    'dashboard.reports': 'Bii',
    'dashboard.alerts': 'Bii',
    'dashboard.users': 'Bii',
  },
  monpa: {
    'nav.home': 'Shi',
    'nav.report': 'Shi',
    'nav.alerts': 'Shi',
    'nav.awareness': 'Shi',
    'nav.login': 'Shi',
    'hero.title': 'Shi',
    'hero.subtitle': 'Shi',
    'hero.report_btn': 'Shi',
    'hero.check_btn': 'Shi',
    'stats.active_alerts': 'Shi',
    'stats.reports_today': 'Shi',
    'stats.water_status': 'Shi',
    'awareness.title': 'Shi',
    'login.title': 'Shi',
    'login.email': 'Shi',
    'login.password': 'Shi',
    'login.submit': 'Shi',
    'login.forgot': 'Shi',
    'login.no_account': 'Shi',
    'login.signup': 'Shi',
    'report.title': 'Shi',
    'report.description': 'Shi',
    'report.name': 'Shi',
    'report.email': 'Shi',
    'report.phone': 'Shi',
    'report.location': 'Shi',
    'report.issue_type': 'Shi',
    'report.symptoms': 'Shi',
    'report.severity': 'Shi',
    'report.submit': 'Shi',
    'alerts.title': 'Shi',
    'alerts.description': 'Shi',
    'alerts.no_alerts': 'Shi',
    'awareness.description': 'Shi',
    'dashboard.welcome': 'Shi',
    'dashboard.overview': 'Shi',
    'dashboard.reports': 'Shi',
    'dashboard.alerts': 'Shi',
    'dashboard.users': 'Shi',
  },
  tripuri: {
    'nav.home': 'Nok',
    'nav.report': 'Nok',
    'nav.alerts': 'Nok',
    'nav.awareness': 'Nok',
    'nav.login': 'Nok',
    'hero.title': 'Nok',
    'hero.subtitle': 'Nok',
    'hero.report_btn': 'Nok',
    'hero.check_btn': 'Nok',
    'stats.active_alerts': 'Nok',
    'stats.reports_today': 'Nok',
    'stats.water_status': 'Nok',
    'awareness.title': 'Nok',
    'login.title': 'Nok',
    'login.email': 'Nok',
    'login.password': 'Nok',
    'login.submit': 'Nok',
    'login.forgot': 'Nok',
    'login.no_account': 'Nok',
    'login.signup': 'Nok',
    'report.title': 'Nok',
    'report.description': 'Nok',
    'report.name': 'Nok',
    'report.email': 'Nok',
    'report.phone': 'Nok',
    'report.location': 'Nok',
    'report.issue_type': 'Nok',
    'report.symptoms': 'Nok',
    'report.severity': 'Nok',
    'report.submit': 'Nok',
    'alerts.title': 'Nok',
    'alerts.description': 'Nok',
    'alerts.no_alerts': 'Nok',
    'awareness.description': 'Nok',
    'dashboard.welcome': 'Nok',
    'dashboard.overview': 'Nok',
    'dashboard.reports': 'Nok',
    'dashboard.alerts': 'Nok',
    'dashboard.users': 'Nok',
  },
  kokborok: {
    'nav.home': 'Nok',
    'nav.report': 'Nok',
    'nav.alerts': 'Nok',
    'nav.awareness': 'Nok',
    'nav.login': 'Nok',
    'hero.title': 'Nok',
    'hero.subtitle': 'Nok',
    'hero.report_btn': 'Nok',
    'hero.check_btn': 'Nok',
    'stats.active_alerts': 'Nok',
    'stats.reports_today': 'Nok',
    'stats.water_status': 'Nok',
    'awareness.title': 'Nok',
    'login.title': 'Nok',
    'login.email': 'Nok',
    'login.password': 'Nok',
    'login.submit': 'Nok',
    'login.forgot': 'Nok',
    'login.no_account': 'Nok',
    'login.signup': 'Nok',
    'report.title': 'Nok',
    'report.description': 'Nok',
    'report.name': 'Nok',
    'report.email': 'Nok',
    'report.phone': 'Nok',
    'report.location': 'Nok',
    'report.issue_type': 'Nok',
    'report.symptoms': 'Nok',
    'report.severity': 'Nok',
    'report.submit': 'Nok',
    'alerts.title': 'Nok',
    'alerts.description': 'Nok',
    'alerts.no_alerts': 'Nok',
    'awareness.description': 'Nok',
    'dashboard.welcome': 'Nok',
    'dashboard.overview': 'Nok',
    'dashboard.reports': 'Nok',
    'dashboard.alerts': 'Nok',
    'dashboard.users': 'Nok',
  },
  bn: {
    'nav.home': 'বাড়ি',
    'nav.report': 'সমস্যা রিপোর্ট করুন',
    'nav.alerts': 'সতর্কতা পরীক্ষা করুন',
    'nav.awareness': 'সচেতনতা',
    'nav.login': 'লগইন',
    'hero.title': 'স্মার্ট কমিউনিটি স্বাস্থ্য পর্যবেক্ষণ ব্যবস্থা',
    'hero.subtitle': 'আপনার সম্প্রদায়ে জলবাহিত রোগের রিপোর্ট, পর্যবেক্ষণ এবং প্রতিরোধ করুন',
    'hero.report_btn': 'স্বাস্থ্য সমস্যা রিপোর্ট করুন',
    'hero.check_btn': 'জলের গুণমান পরীক্ষা করুন',
    'stats.active_alerts': 'সক্রিয় সতর্কতা',
    'stats.reports_today': 'আজকের রিপোর্ট',
    'stats.water_status': 'জলের গুণমানের অবস্থা',
    'awareness.title': 'স্বাস্থ্য সচেতনতা',
    'login.title': 'আপনার একাউন্টে লগইন করুন',
    'login.email': 'ইমেইল ঠিকানা',
    'login.password': 'পাসওয়ার্ড',
    'login.submit': 'সাইন ইন করুন',
    'login.forgot': 'পাসওয়ার্ড ভুলে গেছেন?',
    'login.no_account': 'একাউন্ট নেই?',
    'login.signup': 'সাইন আপ করুন',
    'report.title': 'স্বাস্থ্য সমস্যা রিপোর্ট করুন',
    'report.description': 'স্বাস্থ্য সংক্রান্ত উদ্বেগ রিপোর্ট করে আপনার সম্প্রদায়কে সাহায্য করুন',
    'report.name': 'পূর্ণ নাম',
    'report.email': 'ইমেইল ঠিকানা',
    'report.phone': 'ফোন নম্বর',
    'report.location': 'স্থান/ঠিকানা',
    'report.issue_type': 'সমস্যার ধরন',
    'report.symptoms': 'লক্ষণের বিবরণ',
    'report.severity': 'গুরুত্বের স্তর',
    'report.submit': 'রিপোর্ট জমা দিন',
    'alerts.title': 'স্বাস্থ্য সতর্কতা',
    'alerts.description': 'আপনার এলাকায় স্বাস্থ্য সমস্যাগুলি সম্পর্কে জানুন',
    'alerts.no_alerts': 'কোন সক্রিয় সতর্কতা নেই',
    'awareness.description': 'জলবাহিত রোগ এবং প্রতিরোধ সম্পর্কে জানুন',
    'dashboard.welcome': 'ড্যাশবোর্ডে স্বাগতম',
    'dashboard.overview': 'সামগ্রিক দৃষ্টিভঙ্গি',
    'dashboard.reports': 'রিপোর্টসমূহ',
    'dashboard.alerts': 'সতর্কতাসমূহ',
    'dashboard.users': 'ব্যবহারকারীরা',
  },
  ne: {
    'nav.home': 'घर',
    'nav.report': 'समस्या रिपोर्ट गर्नुहोस्',
    'nav.alerts': 'अलर्ट जाँच गर्नुहोस्',
    'nav.awareness': 'जागरूकता',
    'nav.login': 'लगइन',
    'hero.title': 'स्मार्ट समुदाय स्वास्थ्य निगरानी प्रणाली',
    'hero.subtitle': 'आफ्नो समुदायमा जलजन्य रोगको रिपोर्ट, निगरानी र रोकथाम गर्नुहोस्',
    'hero.report_btn': 'स्वास्थ्य समस्या रिपोर्ट गर्नुहोस्',
    'hero.check_btn': 'पानीको गुणस्तर जाँच गर्नुहोस्',
    'stats.active_alerts': 'सक्रिय अलर्टहरू',
    'stats.reports_today': 'आजका रिपोर्टहरू',
    'stats.water_status': 'पानीको गुणस्तरको स्थिति',
    'awareness.title': 'स्वास्थ्य जागरूकता',
    'login.title': 'आफ्नो खातामा लगइन गर्नुहोस्',
    'login.email': 'इमेल ठेगाना',
    'login.password': 'पासवर्ड',
    'login.submit': 'साइन इन गर्नुहोस्',
    'login.forgot': 'पासवर्ड बिर्सनुभयो?',
    'login.no_account': 'खाता छैन?',
    'login.signup': 'साइन अप गर्नुहोस्',
    'report.title': 'स्वास्थ्य समस्या रिपोर्ट गर्नुहोस्',
    'report.description': 'स्वास्थ्य सम्बन्धी चिन्ता रिपोर्ट गरेर आफ्नो समुदायलाई सहयोग गर्नुहोस्',
    'report.name': 'पूर्ण नाम',
    'report.email': 'इमेल ठेगाना',
    'report.phone': 'फोन नम्बर',
    'report.location': 'स्थान/ठेगाना',
    'report.issue_type': 'समस्याको प्रकार',
    'report.symptoms': 'लक्षणहरूको विवरण',
    'report.severity': 'गम्भीरताको स्तर',
    'report.submit': 'रिपोर्ट पेश गर्नुहोस्',
    'alerts.title': 'स्वास्थ्य अलर्टहरू',
    'alerts.description': 'आफ्नो क्षेत्रमा स्वास्थ्य समस्याहरूको बारेमा जानकारी राख्नुहोस्',
    'alerts.no_alerts': 'कुनै सक्रिय अलर्ट छैन',
    'awareness.description': 'जलजन्य रोगहरू र तिनको रोकथामको बारेमा जान्नुहोस्',
    'dashboard.welcome': 'ड्यासबोर्डमा स्वागत छ',
    'dashboard.overview': 'सिंहावलोकन',
    'dashboard.reports': 'रिपोर्टहरू',
    'dashboard.alerts': 'अलर्टहरू',
    'dashboard.users': 'प्रयोगकर्ताहरू',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState<Language>(languages[0]);

  // Sync with i18n on mount
  useEffect(() => {
    const currentLang = languages.find(lang => lang.code === i18n.language) || languages[0];
    setCurrentLanguage(currentLang);
  }, []);

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language);
    i18n.changeLanguage(language.code);
  };

  const t = (key: string): string => {
    return translations[currentLanguage.code]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, languages, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}